### ISSUE TITLE
Load non-icount snapshot

### ISSUE THREAD

**Issue by branylagaffe** [parsa-epfl/qemu#71]
### Description
QEMU does not allow for block device snapshot made with `icount` disabled to be loaded when `icount` is enabled 

### Steps to Reproduce
1. Boot any type of image
2. save snapshot using the monitor `savevm [name]`
3. quit
4. start new QEMU instance with '-icount` and `loadvm [name]`

### Expected Behavior
Qemu initial check when loading a checkpoint should be discarded

### Additional Information
- QEMU Version/Branch: 8.2.2, master
- Target Architecture: `arm64`

**Comment by branylagaffe** [comment]
@ayanchak1508 @xusine Can you either open a PR regarding this (referencing this issue) or post the patch here ??

**Comment by branylagaffe** [comment]
After discussion, if the icount can be inferred from its snapshot, this should be used to decide whether icount is zeroed or not.

**Comment by BugraEryilmaz** [comment]
[71c4e5f820483633ca7d93f606f2c5fece2d4821](https://github.com/parsa-epfl/qemu/commit/71c4e5f820483633ca7d93f606f2c5fece2d4821)

**Comment by branylagaffe** [comment]
For documentation, @BugraEryilmaz @xusine, what side effects does it induce, if any ?

**Comment by BugraEryilmaz** [comment]
It cannot load icount-enabled snapshots that were created previously with this fix I think
